version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: helios_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "admin123."
      POSTGRES_DB: heliosdb
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: helios_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

volumes:
  postgres_data:
